### ISSUE TITLE
App commands seem to work fine but color blasts for 1 second then off

### ISSUE THREAD

**Issue by sk8tingusmc** [jimbobbennett/NeopixelHolidayLights#1]
I can switch colors and they will appear, but briefly like 1 second each and then automatically go off leaving the off command useless. I believe I have followed all the steps, maybe I missed some part in the code that will keep the lights shining until I send the off command.

**Comment by jimbobbennett** [comment]
The lights should be on until it receives a command to change the lights to off. Can you post your code?

**Comment by sk8tingusmc** [comment]
Thanks, it all works now. It must have been an issue with the strand of lights I was using.
